pipeline {
  agent {
    docker { image 'node:16-alpine' }
  }
  stages {
    stage('Build') {
      steps {
        echo "Build Started..."
        echo "Build Completed..."
      }
    }
    stage('Test') {
      steps {
        echo "Test Started..."
        echo "Test Completed..."
      }
    }
  }
}